

<CreateAccountWindow>:
    name: "create"

    namee: namee
    email: email
    password: passw

    FloatLayout:
        cols:1

        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "Create an Account"
                color:(1,0,0,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4


            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8}
                text: "School Name: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8}
                size_hint: 0.4, 0.12
                id: namee
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13}
                text: "user name:"
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13}
                size_hint: 0.4, 0.12
                id: email
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13*2}
                text: "Password: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13*2}
                size_hint: 0.4, 0.12
                id: passw
                multiline: False
                password: True
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.1}
            size_hint: 0.5, 0.1
            font_size: (root.width**2 + root.height**2) / 15**4
            text: "Already have an Account? Log In"
            color:(1,0,0,1)
            on_release:
                root.manager.transition.direction = "left"
                root.login()

        Button:
            pos_hint:{"x":0.3,"y":0.25}
            size_hint: 0.3, 0.1
            text: "SUBMIT"
            color:(0,1,0,1)
            font_size: (root.width**2 + root.height**2) / 14**4
            on_release:
                root.manager.transition.direction = "left"
                root.submit()


<LoginWindow>:
    name: "login"

    email: email
    password: password

    FloatLayout:
        cols:1

        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "                                WELCOME \n ( SCHOOL FEE MANAGEMENT SYSTEM )"
                color:(1,0,0,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4


            Label:
                text:"user name: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 13**4
                pos_hint: {"x":0.1, "top":0.8}
                size_hint: 0.35, 0.1

            TextInput:
                id: email
                font_size: (root.width**2 + root.height**2) / 13**4
                multiline: False
                pos_hint: {"x": 0.45 , "top":0.8}
                size_hint: 0.4, 0.1

            Label:
                text:"Password: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 13**4
                pos_hint: {"x":0.1, "top":0.6}
                size_hint: 0.35, 0.1

            TextInput:
                id: password
                font_size: (root.width**2 + root.height**2) / 13**4
                multiline: False
                password: True
                pos_hint: {"x": 0.45, "top":0.6}
                size_hint: 0.4, 0.1

            Button:
                pos_hint:{"x":0.05,"y":0.3}
                size_hint: 0.4, 0.1
                font_size: (root.width**2 + root.height**2) / 13**4
                text: "LOGIN"
                color:(0,1,0,1)
                on_release:
                    root.manager.transition.direction = "up"
                    root.loginBtn()

            Button:
                pos_hint:{"x":0.5,"y":0.3}
                size_hint: 0.4, 0.1
                font_size: (root.width**2 + root.height**2) / 13**4
                text: "REGISTER"
                color:(1,0,0,1)
                on_release:
                    root.manager.transition.direction = "right"
                    root.createBtn()

<GetReady>:

    FloatLayout:

        Button:
            pos_hint:{"x":0.3,"top":0.8}
            size_hint: 0.4, 0.1
            font_size: (root.width**2 + root.height**2) / 14**4
            text: "enter fee structure"
            on_release:
                root.manager.transition.direction = "left"
                root.fee()

        Button:
            pos_hint:{"x":0.3,"top":0.6}
            size_hint: 0.4, 0.1
            font_size: (root.width**2 + root.height**2) / 14**4
            text: "enter student details"
            on_release:
                root.manager.transition.direction = "left"
                root.student()

<FeeStructure>:

    clas:clas
    afee:afee
    tfee:tfee
    efee:efee
    oth:oth


    FloatLayout:
        cols:1

        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "enter fee details"
                color:(1,0,0,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8}
                text: "class: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8}
                size_hint: 0.4, 0.12
                id: clas
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13}
                text: "admission fee:"
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13}
                size_hint: 0.4, 0.12
                id: afee
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13*2}
                text: "tuition fee: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13*2}
                size_hint: 0.4, 0.12
                id: tfee
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13*3}
                text: "exam fee: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13*3}
                size_hint: 0.4, 0.12
                id: efee
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.8-0.13*4}
                text: "others: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.13*4}
                size_hint: 0.4, 0.12
                id: oth
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Button:
                pos_hint:{"x":0.1,"top":0.15}
                size_hint: 0.3, 0.1
                font_size: (root.width**2 + root.height**2) / 14**4
                text: "feed"
                on_release:
                    root.manager.transition.direction = "left"
                    root.feed()

            Button:
                pos_hint:{"x":0.5,"top":0.15}
                size_hint: 0.3, 0.1
                font_size: (root.width**2 + root.height**2) / 14**4
                text: "return"
                on_release:
                    root.manager.transition.direction = "left"
                    root.ret()


<MainWindow>:

    FloatLayout:

        Button:
            pos_hint:{"x":0.2, "top": 0.9}
            size_hint:0.5,0.1
            font_size: (root.width**2 + root.height**2) / 14**4
            text: "New student"
            on_release:
                root.manager.transition.direction = "left"
                root.newstudent()

        Button:
            pos_hint:{"x":0.2, "top": 0.75}
            size_hint:0.5,0.1
            font_size: (root.width**2 + root.height**2) / 14**4
            text: "Edit student"
            on_release:
                root.manager.transition.direction = "left"
                root.editstu()

        Button:
            pos_hint:{"x":0.2, "top": 0.6}
            size_hint:0.5,0.1
            font_size: (root.width**2 + root.height**2) / 14**4
            text: "Payment"
            on_release:
                root.manager.transition.direction = "left"
                root.payfee()

        Button:
            pos_hint:{"x":0.2, "top": 0.45}
            size_hint:0.5,0.1
            font_size: (root.width**2 + root.height**2) / 14**4
            text: "Display"
            on_release:
                root.manager.transition.direction = "left"
                root.print()

        Button:
            pos_hint:{"x":0.3, "top": 0.3}
            size_hint:0.3,0.1
            font_size: (root.width**2 + root.height**2) / 14**4
            text: "LOGOUT"
            on_release:
                root.manager.transition.direction = "left"
                root.logout()



<NewStudent>:
    snamee: snamee
    fnamee: fnamee
    dobe: dobe
    classe: classe
    admission: admission
    mobile: mobile

    FloatLayout:
        cols:1

        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "enter new student details"
                color:(1,0,0,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.108
                pos_hint: {"x":0, "top":0.8}
                text: "Student Name: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8}
                size_hint: 0.4, 0.08
                id: snamee
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10}
                text: "father name:"
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.10}
                size_hint: 0.4, 0.08
                id: fnamee
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10*2}
                text: "date of birth: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.10*2}
                size_hint: 0.4, 0.08
                id: dobe
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10*3}
                text: "class: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.10*3}
                size_hint: 0.4, 0.08
                id: classe
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10*4}
                text: "admission number: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.10*4}
                size_hint: 0.4, 0.08
                id: admission
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10*5}
                text: "mobile number: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.10*5}
                size_hint: 0.4, 0.08
                id: mobile
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Button:
                pos_hint:{"x":0.2,"y":0.01}
                size_hint: 0.3, 0.12
                text: "Submit"
                font_size: (root.width**2 + root.height**2) / 14**4
                on_release:
                    root.manager.transition.direction = "left"
                    root.submit()
            Button:
                pos_hint:{"x":0.5,"y":0.01}
                size_hint: 0.3, 0.12
                text: "back"
                font_size: (root.width**2 + root.height**2) / 14**4
                on_release:
                    root.manager.transition.direction = "left"
                    root.back()



<Display>:


    FloatLayout:

        Label:
            id:class_details
            size_hint: 0.5, 0.12
            pos_hint: {"x":0, "top":0.7}
            font_size: (root.width**2 + root.height**2) / 14**4


        Spinner:

            id: spinner_id
            text:"select class"
            values: ["1", "2", "3", "4", "5"]
            size_hint: None, None
            size: 200, 50
            pos_hint:{'center_x':.5, 'top': 0.9}
            on_text: root.spinner_clicked(spinner_id.text)

        Button:
            pos_hint:{"x":0.3,"top":0.2}
            size_hint: 0.3, 0.12
            text: "back"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_release:
                root.manager.transition.direction = "left"
                root.back1()

<Payment>:

    sname2:sname2
    fname1:fname1
    clas1:clas1
    tot:tot
    paid:paid
    balance:balance
    amt:amt
    adm:adm

    FloatLayout:
        cols:1

        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "Admission number"
                color:(0,0,1,1)
                size_hint: 0.5, 0.1
                pos_hint: {"x":0, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.4, "top":0.95}
                size_hint: 0.2, 0.1
                id: adm
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
            Button:
                pos_hint:{"x":0.7, "top": 0.95}
                size_hint:0.3,0.1
                font_size: (root.width**2 + root.height**2) / 14**4
                text: "Get details"
                on_release:
                    root.manager.transition.direction = "left"
                    root.getbal()

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.85}
                text: "student name: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                pos_hint: {"x":0.5, "top":0.85}
                size_hint: 0.4, 0.12
                id: sname2
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.85-0.10}
                text: "father name:"
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                pos_hint: {"x":0.5, "top":0.85-0.10}
                size_hint: 0.4, 0.12
                id: fname1
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.85-0.10*2}
                text: "class: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                pos_hint: {"x":0.5, "top":0.85-0.10*2}
                size_hint: 0.4, 0.12
                id: clas1
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.85-0.10*3}
                text: "total: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                id: tot
                color:(0,0,1,1)
                size_hint: 0.5,0.12
                pos_hint: {"x":0.5, "top":0.85-0.10*3}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.85-0.10*4}
                text: "paid: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                id: paid
                color:(0,0,1,1)
                size_hint: 0.5,0.12
                pos_hint: {"x":0.5, "top":0.85-0.10*4}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.12
                pos_hint: {"x":0, "top":0.85-0.10*5}
                text: "balance: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                id: balance
                color:(0,0,1,1)
                size_hint: 0.5,0.12
                pos_hint: {"x":0.5, "top":0.85-0.10*5}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.1
                pos_hint: {"x":0, "top":0.85-0.10*6}
                text: "amount to be paid: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.85-0.10*6}
                size_hint: 0.3, 0.1
                id: amt
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
            Button:
                pos_hint:{"x":0.1, "top": 0.13}
                size_hint:0.3,0.1
                font_size: (root.width**2 + root.height**2) / 14**4
                text: "SUBMIT"
                on_release:
                    root.manager.transition.direction = "left"
                    root.submit()
            Button:
                pos_hint:{"x":0.5, "top": 0.13}
                size_hint:0.3,0.1
                font_size: (root.width**2 + root.height**2) / 14**4
                text: "BACK"
                on_release:
                    root.manager.transition.direction = "left"
                    root.back()

<EditStudent>:

    sname3:sname3
    fname3:fname3
    clas3:clas3
    dobe3:dobe3
    mob3:mob3
    bal3:bal3
    adm:adm

    FloatLayout:
        cols:1

        FloatLayout:
            size: root.width, root.height/2

            Label:
                text: "Admission number"
                color:(0,0,1,1)
                size_hint: 0.4, 0.1
                pos_hint: {"x":0, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.4, "top":0.95}
                size_hint: 0.2, 0.1
                id: adm
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
            Button:
                pos_hint:{"x":0.65, "top": 0.95}
                size_hint:0.3,0.1
                font_size: (root.width**2 + root.height**2) / 14**4
                text: "Get details"
                on_release:
                    root.manager.transition.direction = "left"
                    root.getdet()
            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8}
                text: "student name: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8}
                size_hint: 0.4, 0.08
                id: sname3
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10}
                text: "father name:"
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.10}
                size_hint: 0.4, 0.08
                id: fname3
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10*2}
                text: "date of birth: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.10*2}
                size_hint: 0.4, 0.08
                id: dobe3
                font_size: (root.width**2 + root.height**2) / 14**4
            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10*3}
                text: "class: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.10*3}
                size_hint: 0.4, 0.08
                id: clas3
                font_size: (root.width**2 + root.height**2) / 14**4
            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10*4}
                text: "mobile: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                pos_hint: {"x":0.5, "top":0.8-0.10*4}
                size_hint: 0.4, 0.08
                id: mob3
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                size_hint: 0.5,0.08
                pos_hint: {"x":0, "top":0.8-0.10*5}
                text: "balance: "
                color:(0,0,1,1)
                font_size: (root.width**2 + root.height**2) / 14**4

            TextInput:
                id: bal3
                size_hint: 0.4,0.08
                pos_hint: {"x":0.5, "top":0.8-0.10*5}
                font_size: (root.width**2 + root.height**2) / 14**4

            Button:
                pos_hint:{"x":0.1, "top": 0.15}
                size_hint:0.3,0.1
                font_size: (root.width**2 + root.height**2) / 14**4
                text: "submit"
                on_release:
                    root.manager.transition.direction = "left"
                    root.submit()
            Button:
                pos_hint:{"x":0.5, "top": 0.15}
                size_hint:0.3,0.1
                font_size: (root.width**2 + root.height**2) / 14**4
                text: "back"
                on_release:
                    root.manager.transition.direction = "left"
                    root.back()
